"""Payment API router — order creation, callback, history."""

import uuid

from fastapi import APIRouter, Depends, Query, Request
from sqlalchemy.ext.asyncio import AsyncSession

from api.dependencies import get_db
from app.dependencies import get_current_user
from app.exceptions import AppException
from app.models.user import User
from app.schemas.payment import (
    CreateOrderRequest,
    CreateOrderResponse,
    PaymentCallbackResponse,
    PaymentHistoryItem,
    PaymentHistoryResponse,
)
from app.services import payment_service

router = APIRouter(prefix="/api/payment", tags=["payment"])


@router.post("/orders", response_model=CreateOrderResponse)
async def create_order(
    body: CreateOrderRequest,
    request: Request,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Create a payment order. Requires JWT cookie."""
    record = await payment_service.create_order(
        db=db,
        user_id=user.id,
        amount=body.amount,
        method=body.method,
    )

    # Generate simulated pay URL with HMAC signature for V1
    sim_transaction_id = f"sim_txn_{uuid.uuid4().hex[:16]}"
    sig = payment_service.sign_callback(record.id, sim_transaction_id)
    pay_url = (
        f"/api/payment/callback/{record.method}"
        f"?order_id={record.id}"
        f"&transaction_id={sim_transaction_id}"
        f"&sig={sig}"
    )

    return CreateOrderResponse(
        order_id=record.id,
        amount=record.amount,
        method=record.method,
        status=record.status,
        pay_url=pay_url,
        created_at=record.created_at,
    )


@router.post("/callback/{method}", response_model=PaymentCallbackResponse)
async def payment_callback(
    method: str,
    order_id: int = Query(..., gt=0),
    transaction_id: str = Query(..., min_length=1),
    sig: str = Query(..., min_length=32, max_length=32),
    db: AsyncSession = Depends(get_db),
):
    """Handle payment gateway callback.

    V1: HMAC-signed simulated callback. The `sig` parameter validates that
    the callback URL was generated by this server, preventing enumeration.
    Production: Replace with Alipay/WeChat signature verification middleware.
    """
    # Verify HMAC signature
    if not payment_service.verify_callback_signature(order_id, transaction_id, sig):
        raise AppException(403, "无效的签名", "INVALID_SIGNATURE")

    record = await payment_service.handle_callback(
        db=db,
        method=method,
        order_id=order_id,
        transaction_id=transaction_id,
    )

    return PaymentCallbackResponse(
        order_id=record.id,
        amount=record.amount,
        method=record.method,
        status=record.status,
        transaction_id=record.transaction_id or "",
    )


@router.get("/history", response_model=PaymentHistoryResponse)
async def get_payment_history(
    request: Request,
    page: int = Query(1, ge=1),
    page_size: int = Query(20, ge=1, le=100),
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Get paginated payment history for the current user. Requires JWT cookie."""
    items, total = await payment_service.get_payment_history(
        db=db,
        user_id=user.id,
        page=page,
        page_size=page_size,
    )

    return PaymentHistoryResponse(
        items=[
            PaymentHistoryItem(
                id=item.id,
                amount=item.amount,
                method=item.method,
                status=item.status,
                transaction_id=item.transaction_id,
                created_at=item.created_at,
            )
            for item in items
        ],
        total=total,
        page=page,
        page_size=page_size,
    )
